apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  type: NodePort # or LoadBalancer if you want external access
  ports:
    - name: web
      port: 9093
      targetPort: 9093
      nodePort: 31093 # Optional, for NodePort
  selector:
    app: alertmanager
