apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1-service-account.yaml
  - 2-configmap.yaml
  - 3-pvc.yaml
  - 4-secret.yaml
  - 5-deployment.yaml
  - 6-service.yaml
  - 7-service-monitor.yaml
