apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 1-loki-config.yaml
  - 2-loki-pvc.yaml
  - 3-loki-deployment.yaml
  - 4-loki-service.yaml
  - 5-promtail-daemonset.yaml
  - 6-promtail-config.yaml
  - 7-promtail-clusterrole.yaml
  - 8-promtail-pvc.yaml
  - 9-promtail-service-account.yaml
  - 10-promtail.rolebinding.yaml

