apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.internal.uia.no/ikt210-g-24h-skyinfrastruktur/LabGroup21/final-project.git
    path: monitoring-stack/prometheus-operator
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true