apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 0-namespace.yaml
  - 1-service-account.yaml
  - 2-cluster-role.yaml
  - 3-cluster-role-binding.yaml
  - 4-deployment.yaml
  - 5-service.yaml
  - 6-service-monitor.yaml