apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./crds
  - ./metrics-server
  - ./prometheus-operator
  - ./prometheus
  - ./alertmanager
  - ./node-exporter
  - ./grafana
  - ./loki