apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-demo-db-prometheus-demo-0
  namespace: monitoring
  labels:
    app: prometheus
    prometheus: demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path